### ISSUE TITLE
unknown module Error

### ISSUE THREAD

**Issue by tpospisil** [szkiba/xk6-yaml#3]
I am getting an error while running a k6 script which attempts to import module `k6/x/yaml`. I am running the below command to build the k6 binary with xk6.
```
xk6 build --with github.com/szkiba/xk6-yaml@latest
```
The binary is building successfully.

I am attempting to run my script (which works without `import { parse } from "k6/x/yaml";`) via the following command:
```
k6 run performance/policy_k6.js
```

And I am running into the below error:
```
ERRO[0000] unknown module: k6/x/yaml
	at go.k6.io/k6/js.(*InitContext).Require-fm (native)
	at file:///Users/tylerpospisil/projects/system-tests/performance/policy_k6.js:4:0(43)  hint="script exception"
```

**OS:** macOS Big Sur (11.3.1)
**Go version:** go version go1.18.1 darwin/amd64

Any help would be greatly appreciated! Thanks in advance.

**Comment by szkiba** [comment]
@tpospisil  you should custom builded k6 from current directory: ./k6
