### ISSUE TITLE
package for type definitions

### ISSUE THREAD

**Issue by nathanloyer** [szkiba/xk6-yaml#4]
I see you have typescript definitions, but I haven't found a way to install them other than directly from this repo. Are they published anywhere? If not, it would be helpful to make that available. For now I'll copy the .d.ts to my code and put the proper namespacing in there.

**Comment by szkiba** [comment]
@nathanloyer no, currently not published. I found compliated to publish it as npm package (since k6 is not a typical js runtime).
BTW I would welcome any solutions...

**Comment by nathanloyer** [comment]
So the way my repo is set up.. it's using webpack to transpile the typescript to k6-compatible javascript. So at that point, you can manage the type definitions the way you would for any nodejs project. What would probably be the easiest for you is to add the definitions to the DefinitelyTyped repo which can publish the definitions for you to `@types/xk6-yaml` if you set up a directory in there for it. 

As an example here are the type definitions for k6 in general:

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/k6

I can chat more with you about this if needed. It's been a few months since I was looking at this, so I may need to refresh my memory further. We were able to work around the issue in our repo by making a manual .d.ts file for this code.
